### ISSUE TITLE
Error : in MetroListView.js

### ISSUE THREAD

**Issue by sanjeev-iitr-uk** [react-native-web-community/react-native-web-lists#4]
![image](https://user-images.githubusercontent.com/14174395/39816007-80e972e2-53b7-11e8-8dbb-60b95811c81f.png)

**Comment by Minishlink** [comment]
Add `/node_modules\/react-native-/,` to the list of included packages that goes through babel in your webpack config. Or send a PR to transpile before publishing to npm.
